### ISSUE TITLE
DateTime tests fail

### ISSUE THREAD

**Issue by benkasminbullock** [jforget/Astro-Sunrise#16]
The 06datetime.t tests fail on my system like this:

    Cannot determine local time zone

For example you could change the BEGIN block in the test like this:

    BEGIN {
      eval "use DateTime;my \$sunrise_1 = sun_rise( -118, 33  );";

In this way the functioning of DateTime could be tested before running it.

Other than that the module installs correctly.

**Comment by jforget** [comment]
What is your operating system? If you check CPAN testers at http://matrix.cpantesters.org/?dist=Astro-Sunrise+0.98, you will find that there is one "red" result, which comes from the only tester using Haiku OS. This is not new and I have mentioned this problem in the "Haiku OS" subchapter of the BUGS chapter of the POD documentation, see https://metacpan.org/pod/Astro::Sunrise#Haiku-OS-CPAN-Tester.

**Comment by benkasminbullock** [comment]
> What is your operating system?

FreeBSD. My time zone is set to Japan Standard Time:

````
$ date
Mon Feb  1 16:04:32 JST 2021
````

I thought I should check my system, so I ran tzsetup as described here:

https://linuxhint.com/change-freebsd-timezone-2/

Oddly enough that solved the problem with your module, so it looks like there might have been something wrong with my setup.

> If you check CPAN testers at http://matrix.cpantesters.org/?dist=Astro-Sunrise+0.98, you will find that there is one "red" result, which comes from the only tester using Haiku OS. This is not new and I have mentioned this problem in the "Haiku OS" subchapter of the BUGS chapter of the POD documentation, see https://metacpan.org/pod/Astro::Sunrise#Haiku-OS-CPAN-Tester.

I don't know what HaikuOS is. The fix I suggested above will work around problems like this. But now it looks like a possible problem with my OS setup, so I'll close this to save further work for you.

**Comment by jforget** [comment]
What is Haiku-OS ? It is a new version of Be OS. Do not ask me what is Be OS, I never used it.

I do not think your suggested workaround is the proper one. If *my* module breaks, I want to be aware of it. The call to "sun_rise" should be outside the "eval". But is some *other* module breaks, my test script should be able to cancel and skip the tests. Only if the break is caused by another module.

What I really should do is install a virtual machine with a incomplete setup, that is, without specifying the timezone. And then, test Astro::Sunrise in this virtual machine.

But for the moment, this is a very low priority issue. I will come back to it at some time in the future, but not the near future. You closed the issue. I leave it closed for the moment. Thank you anyway.
